### PR TITLE
Points polymer UI at cocoMDS2 where all functionality then works

### PR DESCRIPTION
**Pull request by cmgrote**
at least as aligned to the labs as they are being re-worked via https://github.com/odpi/egeria/pull/5462

### CODE REVIEW

**Comment by cmgrote** [comment]
@planetf1 not sure if I've done everything I needed to for it to be "ready for release" as a new chart version?  Would ideally like to get these changes included ASAP for further development of the draft lineage lab...

**Comment by cmgrote** [comment]
Nevermind, I think I've managed to put the configuration into the Notebook in the lab to match what was originally defined here in the chart.

**Comment by planetf1** [comment]
> @planetf1 not sure if I've done everything I needed to for it to be "ready for release" as a new chart version? Would ideally like to get these changes included ASAP for further development of the draft lineage lab...

For future ref, yes I think that should be sufficient.

**Comment by mandy-chessell** [comment]
The polymer UI should be using cocoMDS4 to be consistent with the scenario.  cocoMDS2 is the governance metadata server and sees incomplete assets in the quarantine zone.   cocoMDS4 is exposed to assets that are complete and is the right connection point for lineage and the asset search for the data lake users.

I understand that its version of TEX does not work on cocoMDS4 but as soom as it is fixed we need to move the UI to its proper connection point.

**Comment by cmgrote** [comment]
Have left the chart as-is and closed rather than merged the PR.

**Pull request closed without merging**
